# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import queue
import sys
import threading
import time

import cv2


import src.CSimg.res_rc
from PyQt5 import QtCore, QtGui, QtWidgets
from src.CSimg.contrl_ui.contrl import ContrlWindow
from PyQt5.QtGui import QPixmap, QImage
import src.CSimg.server


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1648, 1235)
        MainWindow.setStyleSheet("QLabel{\n"
                                 "    border: 2px solid rgb(209, 130, 255);\n"
                                 "}\n"
                                 "#frame_2{\n"
                                 "    border-top-left-radius:50px;\n"
                                 "    border-top-right-radius:50px;\n"
                                 "    background-color: rgb(209, 130, 255);\n"
                                 "    \n"
                                 "}\n"
                                 "#frame_3{\n"
                                 "    background-color: rgb(109, 10, 200);\n"
                                 "}\n"
                                 "\n"
                                 "#frame_4{\n"
                                 "    \n"
                                 "    background-color: rgba(222, 188, 255,128);\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "#frame_5{\n"
                                 "    background-color: rgb(29, 10, 10);\n"
                                 "}\n"
                                 "\n"
                                 "#frame_6{\n"
                                 "    background-color: rgb(29, 10, 100);    \n"
                                 "}\n"
                                 "\n"
                                 "#frame_7{\n"
                                 "    background-color: rgb(29, 101, 100);    \n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 1600, 1060))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1600, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.version_info = QtWidgets.QLabel(self.frame_2)
        self.version_info.setGeometry(QtCore.QRect(1290, 20, 131, 31))
        self.version_info.setObjectName("version_info")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(1430, 10, 141, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min_button = QtWidgets.QPushButton(self.layoutWidget)
        self.min_button.setStyleSheet("image: url(:/icon/icon/minus.png);\n"
                                      "background-color: rgba(255, 255, 255, 0);")
        self.min_button.setText("")
        self.min_button.setObjectName("min_button")
        self.horizontalLayout.addWidget(self.min_button)
        #         self.expend_button = QtWidgets.QPushButton(self.layoutWidget)
        #         self.expend_button.setStyleSheet("image: url(:/icon/icon/expand.png);\n"
        # "background-color: rgba(255, 255, 255, 0);")
        #         self.expend_button.setText("")
        #         self.expend_button.setObjectName("expend_button")
        #         self.horizontalLayout.addWidget(self.expend_button)
        self.close_button = QtWidgets.QPushButton(self.layoutWidget)
        self.close_button.setStyleSheet("image: url(:/icon/icon/close.png);\n"
                                        "background-color: rgba(255, 255, 255, 0);")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(320, 200, 1280, 720))
        self.frame_3.setStyleSheet("background-image: url(:/icon/img/noConnet.png);\n"
                                   "")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.maplabel = QtWidgets.QLabel(self.frame_3)
        self.maplabel.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.maplabel.setText("")
        self.maplabel.setObjectName("maplabel")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 50, 1600, 150))
        self.frame_4.setStyleSheet("#LaunchContrl{\n"
                                   "    image: url(:/icon/icon/th-large.png);\n"
                                   "    \n"
                                   "    background-color: rgba(211, 255, 216,0);\n"
                                   "}\n"
                                   "#LaunchContrl:hover{\n"
                                   "    background-color: rgb(162, 139, 255);\n"
                                   "\n"
                                   "}\n"
                                   "")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.carinfor_2 = QtWidgets.QFrame(self.frame_4)
        self.carinfor_2.setGeometry(QtCore.QRect(800, 0, 400, 150))
        self.carinfor_2.setStyleSheet("background-color: rgb(205, 216, 255);")
        self.carinfor_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carinfor_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carinfor_2.setObjectName("carinfor_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.carinfor_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(240, 0, 161, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.car2_x = QtWidgets.QLabel(self.layoutWidget1)
        self.car2_x.setObjectName("car2_x")
        self.verticalLayout_2.addWidget(self.car2_x)
        self.car2_y = QtWidgets.QLabel(self.layoutWidget1)
        self.car2_y.setObjectName("car2_y")
        self.verticalLayout_2.addWidget(self.car2_y)
        self.car2_info = QtWidgets.QLabel(self.layoutWidget1)
        self.car2_info.setObjectName("car2_info")
        self.verticalLayout_2.addWidget(self.car2_info)
        self.car2_no = QtWidgets.QLabel(self.carinfor_2)
        self.car2_no.setGeometry(QtCore.QRect(0, 0, 200, 150))
        self.car2_no.setStyleSheet("font: 20pt \"Berlin Sans FB\";")
        self.car2_no.setObjectName("car2_no")
        self.carinfor_3 = QtWidgets.QFrame(self.frame_4)
        self.carinfor_3.setGeometry(QtCore.QRect(1200, 0, 400, 150))
        self.carinfor_3.setStyleSheet("background-color: rgb(171, 177, 255);")
        self.carinfor_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carinfor_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carinfor_3.setObjectName("carinfor_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.carinfor_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(240, 0, 161, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.car3_x = QtWidgets.QLabel(self.layoutWidget_2)
        self.car3_x.setObjectName("car3_x")
        self.verticalLayout_3.addWidget(self.car3_x)
        self.car3_y = QtWidgets.QLabel(self.layoutWidget_2)
        self.car3_y.setObjectName("car3_y")
        self.verticalLayout_3.addWidget(self.car3_y)
        self.car3_info = QtWidgets.QLabel(self.layoutWidget_2)
        self.car3_info.setObjectName("car3_info")
        self.verticalLayout_3.addWidget(self.car3_info)
        self.car3_no = QtWidgets.QLabel(self.carinfor_3)
        self.car3_no.setGeometry(QtCore.QRect(0, 0, 200, 150))
        self.car3_no.setStyleSheet("font: 20pt \"Berlin Sans FB\";")
        self.car3_no.setObjectName("car3_no")
        self.carinfo_1 = QtWidgets.QFrame(self.frame_4)
        self.carinfo_1.setGeometry(QtCore.QRect(400, 0, 400, 150))
        self.carinfo_1.setStyleSheet("background-color: rgb(255, 167, 255);")
        self.carinfo_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carinfo_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carinfo_1.setObjectName("carinfo_1")
        self.car1_no = QtWidgets.QLabel(self.carinfo_1)
        self.car1_no.setGeometry(QtCore.QRect(0, 0, 200, 150))
        self.car1_no.setStyleSheet("font: 20pt \"Berlin Sans FB\";")
        self.car1_no.setObjectName("car1_no")
        self.layoutWidget2 = QtWidgets.QWidget(self.carinfo_1)
        self.layoutWidget2.setGeometry(QtCore.QRect(240, 0, 161, 151))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.car1_x = QtWidgets.QLabel(self.layoutWidget2)
        self.car1_x.setObjectName("car1_x")
        self.verticalLayout.addWidget(self.car1_x)
        self.car1_y = QtWidgets.QLabel(self.layoutWidget2)
        self.car1_y.setObjectName("car1_y")
        self.verticalLayout.addWidget(self.car1_y)
        self.car1_info = QtWidgets.QLabel(self.layoutWidget2)
        self.car1_info.setObjectName("car1_info")
        self.verticalLayout.addWidget(self.car1_info)
        self.Logo = QtWidgets.QLabel(self.frame_4)
        self.Logo.setGeometry(QtCore.QRect(0, 0, 321, 151))
        self.Logo.setStyleSheet("image: url(:/icon/img/img.png);")
        self.Logo.setText("")
        self.Logo.setObjectName("Logo")
        self.LaunchContrl = QtWidgets.QPushButton(self.frame_4)
        self.LaunchContrl.setGeometry(QtCore.QRect(320, 30, 81, 81))
        self.LaunchContrl.setStyleSheet("")
        self.LaunchContrl.setText("")
        self.LaunchContrl.setObjectName("LaunchContrl")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(0, 200, 320, 240))
        self.frame_7.setAutoFillBackground(False)
        self.frame_7.setStyleSheet("background-image: url(:/icon/img/noConnet.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.carlabel_1 = QtWidgets.QLabel(self.frame_7)
        self.carlabel_1.setGeometry(QtCore.QRect(0, 0, 320, 240))
        self.carlabel_1.setStyleSheet("")
        self.carlabel_1.setText("")
        self.carlabel_1.setObjectName("carlabel_1")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(0, 680, 320, 240))
        self.frame_6.setStyleSheet("background-image: url(:/icon/img/noConnet.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.carlabel_3 = QtWidgets.QLabel(self.frame_6)
        self.carlabel_3.setGeometry(QtCore.QRect(0, 0, 320, 240))
        self.carlabel_3.setText("")
        self.carlabel_3.setObjectName("carlabel_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 440, 320, 240))
        self.frame_5.setStyleSheet("background-image: url(:/icon/img/noConnet.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.carlabel_2 = QtWidgets.QLabel(self.frame_5)
        self.carlabel_2.setGeometry(QtCore.QRect(0, 0, 320, 240))
        self.carlabel_2.setText("")
        self.carlabel_2.setObjectName("carlabel_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.version_info.setText(_translate("MainWindow", "0.0.1v --by cc"))
        self.car2_x.setText(_translate("MainWindow", "TextLabel"))
        self.car2_y.setText(_translate("MainWindow", "TextLabel"))
        self.car2_info.setText(_translate("MainWindow", "TextLabel"))
        self.car2_no.setText(_translate("MainWindow", "No.2号小车"))
        self.car3_x.setText(_translate("MainWindow", "TextLabel"))
        self.car3_y.setText(_translate("MainWindow", "TextLabel"))
        self.car3_info.setText(_translate("MainWindow", "TextLabel"))
        self.car3_no.setText(_translate("MainWindow", "No.3号小车"))
        self.car1_no.setText(_translate("MainWindow", "No.1号小车"))
        self.car1_x.setText(_translate("MainWindow", "TextLabel"))
        self.car1_y.setText(_translate("MainWindow", "TextLabel"))
        self.car1_info.setText(_translate("MainWindow", "TextLabel"))


class MyWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MyWindow, self).__init__()

        self.QImg1 = queue.Queue(2)
        self.QImg2 = queue.Queue(2)
        self.QImg3 = queue.Queue(2)
        self.QImg4 = queue.Queue(2)

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Server 用于接收图片
        self.Server = server.Socket_Img()
        self.socket_Handle()
        threading.Thread(target=self.trans_img, daemon=True).start()
        threading.Thread(target=self.run_img, args=(self.ui.carlabel_1,'1',),daemon=True).start()
        threading.Thread(target=self.run_img, args=(self.ui.carlabel_2, '2',), daemon=True).start()
        threading.Thread(target=self.run_img, args=(self.ui.carlabel_3, '3',), daemon=True).start()
        threading.Thread(target=self.run_img, args=(self.ui.maplabel, '4',), daemon=True).start()
        # close
        self.ui.close_button.clicked.connect(self.close)
        # self.expend_button.clicked.connect(MainWindow.showFullScreen)
        self.ui.min_button.clicked.connect(self.showMinimized)
        self.ui.LaunchContrl.clicked.connect(self.OpenContrl)

        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        # 用来更新UI的图片
        # threading.Thread(target=self.Server.Run_Main, daemon=True).start()
        self.show()

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.m_flag = True
            self.m_Position = event.globalPos() - self.pos()  # 获取鼠标相对窗口的位置
            event.accept()
            self.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))  # 更改鼠标图标

    def mouseMoveEvent(self, QMouseEvent):
        if QtCore.Qt.LeftButton and self.m_flag:
            self.move(QMouseEvent.globalPos() - self.m_Position)  # 更改窗口位置
            QMouseEvent.accept()

    def mouseReleaseEvent(self, QMouseEvent):
        self.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))  # 更改鼠标图标
        self.m_flag = False

    def OpenContrl(self):
        self.contrl = ContrlWindow()

    def socket_Handle(self):
        threading.Thread(target=self.Server.Run_Main,daemon=True).start()

    # # 用来更新UI图片
    def trans_img(self):
        noflag1 = 0
        noflag2 = 0
        noflag3 = 0
        noflag4 = 0

        noconnectimg = QPixmap("./img/noConnet.png")
        while True:
            img1 = self.Server.Read_info('1')
            img2 = self.Server.Read_info('2')
            img3 = self.Server.Read_info('3')
            img4 = self.Server.Read_info('map')
            if img1 != None:
                img1 = self.Server.bytes2cv(img1)
                img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
                temp_imgSrc = QImage(img1, img1.shape[1], img1.shape[0], img1.shape[1] * 3,
                                     QImage.Format_RGB888)
                # 将图片转换为QPixmap方便显示
                pixmap_imgSrc = QPixmap.fromImage(temp_imgSrc)
                self.QImg1.put(pixmap_imgSrc)
                noflag1 = 0
            else:
                pixmap_imgSrc = noconnectimg
                if noflag1 != 1:
                    self.QImg1.put(pixmap_imgSrc)
                    noflag1 = 1

            if img2 != None:
                img2 = self.Server.bytes2cv(img2)
                img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
                temp_imgSrc = QImage(img2, img2.shape[1], img2.shape[0], img2.shape[1] * 3,
                                     QImage.Format_RGB888)
                # 将图片转换为QPixmap方便显示
                pixmap_imgSrc = QPixmap.fromImage(temp_imgSrc)
                self.QImg2.put(pixmap_imgSrc)
                noflag2 = 0
            else:
                pixmap_imgSrc = noconnectimg
                if noflag2 != 1:
                    self.QImg2.put(pixmap_imgSrc)
                    noflag2 = 1

            if img3 != None:
                img3 = self.Server.bytes2cv(img3)
                img3 = cv2.cvtColor(img3, cv2.COLOR_BGR2RGB)
                temp_imgSrc = QImage(img3, img3.shape[1], img3.shape[0], img3.shape[1] * 3,
                                     QImage.Format_RGB888)
                # 将图片转换为QPixmap方便显示
                pixmap_imgSrc = QPixmap.fromImage(temp_imgSrc)
                self.QImg3.put(pixmap_imgSrc)
                noflag3 = 0
            else:
                pixmap_imgSrc = noconnectimg
                if noflag3 != 1:
                    self.QImg3.put(pixmap_imgSrc)
                    noflag3 = 1

            if img4 != None:
                img4 = self.Server.bytes2cv(img4)
                img4 = cv2.cvtColor(img4, cv2.COLOR_BGR2RGB)
                temp_imgSrc = QImage(img4, img4.shape[1], img4.shape[0], img4.shape[1] * 3,
                                     QImage.Format_RGB888)
                # 将图片转换为QPixmap方便显示
                pixmap_imgSrc = QPixmap.fromImage(temp_imgSrc)
                self.QImg4.put(pixmap_imgSrc)
                noflag1 = 0
            else:
                pixmap_imgSrc = noconnectimg
                if noflag4 != 1:
                    self.QImg4.put(pixmap_imgSrc)
                    noflag4 = 1


    def run_img(self,label,num):
        noconnectimg = QPixmap("./img/noConnet.png")
        label.setScaledContents(True)
        img = noconnectimg
        while True:
            if num == '1':
                img = self.QImg1.get()
            if num == '2':
                img = self.QImg2.get()
            if num == '3':
                img = self.QImg3.get()
            if num == '4':
                img = self.QImg4.get()
            label.setPixmap(img)
            time.sleep(0.1)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    win = MyWindow()
    sys.exit(app.exec())
